DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER(ID BIGINT PRIMARY KEY,
                      FIRSTNAME VARCHAR(255) NOT NULL,
                      LASTNAME VARCHAR(255) NOT NULL,
                      EMAIL VARCHAR(255) NOT NULL,
                      PASSWORD VARCHAR(255) NOT NULL
              );